Auction and ui
RobinStephenson/jbt-2 pull request #107
Opened 2017-02-20 17:35 UTC by tc975

Finished auction. Done. Complete

closes #14

2017-02-20 23:32 UTC, RobinStephenson requested changes

2017-02-20 23:32 UTC, RobinStephenson commented on Assets/Code/Classes/Agent Hierarchy/AuctionManager.cs
> +﻿// Game Executable hosted at: http://www-users.york.ac.uk/~jwa509/alpha01BugFree.exe
This should be to our download not theres

2017-02-20 23:32 UTC, RobinStephenson commented on Assets/Code/Classes/Agent Hierarchy/AuctionManager.cs
> +﻿// Game Executable hosted at: http://www-users.york.ac.uk/~jwa509/alpha01BugFree.exe
Also needs a created by jbt note

2017-02-20 23:32 UTC, RobinStephenson commented on Assets/Code/Classes/Game Manager/GameManager.cs
> +        ACQUISITION, PURCHASE, INSTALLATION, PRODUCTION, AUCTIONLIST, AUCTIONBID
needs a note saying what we added as this is quite a prominent change

2017-02-20 23:35 UTC, RobinStephenson commented
Requested some very small comment changes but we can just sort them first thing in the morning and then do some play testing. if we dont have time just merge anyway

2017-02-20 23:49 UTC, tc975 commented
@RobinStephenson 
Made the requested changes

2017-02-21 10:09 UTC, RobinStephenson approved these changes

2017-02-21 10:09 UTC, merged