Removed floaty islands from lake
RobinStephenson/jbt-2 pull request #42
Opened 2017-02-06 19:13 UTC by tc975

closes #34 
(csproj changes, not sure if ok)

2017-02-08 11:45 UTC, Mikeywalsh requested changes
Branch has not been updated to latest version of master. Merging now would mess with the build order that I changed.

Apart from that its okay, just merge the branch with master and you're good to go!

2017-02-08 13:18 UTC, RobinStephenson commented
@Mikeywalsh the merge with master is done by resolving the conflicts and github wont let you push without resolving them first

2017-02-09 14:29 UTC, Mikeywalsh commented
Alright, looks good to go then

2017-02-09 14:29 UTC, Mikeywalsh approved these changes

2017-02-09 14:29 UTC, merged