Added tile highlights and fixed help menu
RobinStephenson/jbt-2 pull request #47
Opened 2017-02-08 11:41 UTC by Mikeywalsh

2 Changes:
1. The help box no longer returns after the player has clicked the hide button
2. The entire tile is now highlighted whenever it changes color. This is done via a transparent place. the alpha color of which can be changed in the TileObect class. It is now much easier to see what tile is owned by who, and what is selected!

closes #40  
closes #44

2017-02-11 15:27 UTC, RobinStephenson requested changes
Rather than putting the JBT in the Summary section put it in a comment above the summary. The <summary> should be used for documentation where as the JBT notes are for marking.

A few spots where you haven't mentioned changes

Looks good otherwise

2017-02-11 17:06 UTC, RobinStephenson commented
@Mikeywalsh message me on slack when youve made the changes

2017-02-11 17:12 UTC, Mikeywalsh commented
Changes are done!

2017-02-12 14:01 UTC, RobinStephenson approved these changes

2017-02-13 03:37 UTC, merged